spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
#        default_batch_fetch_size: 100

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://my-db:3306/${MYSQL_DB}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&charaterEncoding=utf-8
#    url: jdbc:mysql://my-db:3306/mydb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&charaterEncoding=utf-8
#    url: jdbc:mysql://localhost:3306/mydb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&charaterEncoding=utf-8
    username: ${MYSQL_USER}
#    username: user
    password: ${MYSQL_PASSWORD}
#    password: user

#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password:
#  h2:
#    console:
#      enabled: true #localhost:8080/h2-console

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type.descriptor.sql.BasicBinder: TRACE